video_device:
  name:       video file
  file:       ../videos/coover02.mp4
  color_mode: bw
  max_height: 480

edge_detector:
  low_threshold:    50
  high_threshold:   150
  kernel_size:      3

slam:
  vocab_file:       ORB_SLAM2/Vocabulary/ORBvoc.bin
  config_file:      slam_config.yml
  visualizer:       true

hough_transform:
  rho:                  1
  theta:                1
  threshold:            180 #90
  min_vertical_angle:   10
  min_horizontal_angle: 5

vanishing_point_detector:
  enabled:              false
  threshold:            10
  iterations:           100

steer_pid:
  kp: 200
  ki: 0
  kd: 0

#robot:
#  port: /dev/ttyUSB0
